language: cpp

compiler:
  - gcc-4.8
  - clang

cache:
  apt: true

before_install:
  - git submodule update --init --recursive
  - sudo apt-get install -qq cmake zlib1g-dev libbz2-dev
  # add PPA with GCC 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  # add PPA with updated Boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  # update packages
  - sudo apt-get update -qq;

install:
  - sudo apt-get install -qq libboost1.54-dev
  - sudo apt-get install -qq gcc-4.8 g++-4.8;
    if [ "$CC" == "gcc" ];
    then
      export CXX=g++-4.8 CC=gcc-4.8;
      gcc-4.8 --version;
    fi

script:
    ./util/travis/linux-cibuild.sh
